### ISSUE TITLE
Update the Outdated Transaction URLs.

### ISSUE THREAD

**Issue by YaMo97** [ArunYogi/paytm-cordova-plugin#12]
Hi @ArunYogi, 

The Transaction URLs in use in this plugin needs to be updated as PayTM is no longer providing Live Credentials to Merchants using old URLs.

A similar problem was noted in issue #9, and thus we have to move away from PayTM to another PG.

Please do the needful as soon as possible.

**Comment by iamsaikat** [comment]
I have updated the plugin. You can try from my repo.

https://github.com/iamsaikat/paytm-cordova-plugin

**Comment by ArunYogi** [comment]
Updated the plugin with latest libraries and released a version of the same as 0.0.5

**Comment by ArunYogi** [comment]
@iamsaikat , Current release to support existing users. I will release another version of this plugin, with few other changes including support for cordova-android-7.*

**Comment by iamsaikat** [comment]
@ArunYogi thanks for the update. Please update paytm SDK via dependencies in upcoming updates. It will be better to use dependencies rather than using library directly.
