### ISSUE TITLE
Redirecting issue

### ISSUE THREAD

**Issue by zebap** [ArunYogi/paytm-cordova-plugin#16]
Its not redirecting me back in my application after success payment

**Comment by ArunYogi** [comment]
@zebap , redirecting issues is in paytm library itself. As per suggestion, I have upgraded paytm plugin version to 1.3.3, which should solve the issue (suggested by Paytm). Please use the latest version and I hope the latest library solves that issue.

**Comment by ArunYogi** [comment]
Redirecting issue is resolved with latest payment plugin release

**Comment by zebap** [comment]
Still not working
