### ISSUE TITLE
We are getting paytmcordova.xml not found

### ISSUE THREAD

**Issue by seoranks** [ArunYogi/paytm-cordova-plugin#18]
.
Failed to install 'cordova-plugin-paytm': CordovaError: Uh oh!
"\plugins\cordova-plugin-paytm\app\src\android\res\values\paytmcordova.xml" not found!

**Comment by BajajSaajan** [comment]
Hi @seoranks 
I'm also trying to install paytm in my ionic 4 application and getting same error. 
Have you got any solution ?

**Comment by BajajSaajan** [comment]
Hi @ArunYogi 
could you please help us for integrate paytm in ionic application ?

**Comment by ArunYogi** [comment]
Corrected the file reference in latest release

**Comment by luckyplayone** [comment]
Hi @ArunYogi 
I am getting this error while opening the paytm. please help asap
{"STATUS":"TXN_FAILURE","ORDERID":"ORDER0000000004","TXNAMOUNT":"1.00","MID":"Playon05025317561797","RESPCODE":"330","BANKTXNID":"","CURRENCY":"INR","RESPMSG":"Paytm checksum mismatch."}

**Comment by ArunYogi** [comment]
@luckyplayone , you have posted the response from Paytm, request to Paytm would be helpful to identify the issue. Further create a new question based issue in github and let's not comment in closed issues.
