### ISSUE TITLE
Need help with options params in function defintion

### ISSUE THREAD

**Issue by rvdfox** [ArunYogi/paytm-cordova-plugin#2]
I was able to setup the plugin properly, but what will go inside options [object] parameter, as i can see paytm page but with broken link.

**Comment by ArunYogi** [comment]
Very sorry for late reply and inconveniences.
I will add this to readme file
Options =

> 
"REQUEST_TYPE": "DEFAULT",
"MID": "PAYTM_MERCHANT_ID",
"ORDER_ID": "ORDER0000000001",
"CUST_ID": "10000988111",
"INDUSTRY_TYPE_ID": "PAYTM_INDUSTRY_TYPE_ID",
"CHANNEL_ID": "WAP",
"TXN_AMOUNT": "1",
"WEBSITE": "PAYTM_WEBSITE",
"CALLBACK_URL": "https://securegw.paytm.in/theia/paytmCallback?ORDER_ID=ORDER0000000001",
"EMAIL": "abc@gmail.com",
"MOBILE_NO": "9999999999",
"ENVIRONMENT":"STAGING",
"CHECKSUMHASH": "w2QDRMgp1/BNdEnJEAPCIOmNgQvsi+BhpqijfM9KvFfRiPmGSt3Ddzw+oTaGCLneJwxFFq5mqTMwJXdQE2EzK4px2xruDqKZjHupz9yXev4="
}
