### ISSUE TITLE
Paytm checksum mismatch

### ISSUE THREAD

**Issue by luckyplayone** [ArunYogi/paytm-cordova-plugin#20]
Hi @ArunYogi 
Please help me for integrating paytm 
Here's my params which I'm sending while generating checksum hash
  let params = {
      REQUEST_TYPE: "DEFAULT",
      MID: "Playon05025317561797",
      ORDER_ID: "ORDER0000000005",
      CUST_ID: "CUSTID_0000000005",
      INDUSTRY_TYPE_ID: "Retail",
      CHANNEL_ID: "WAP",
      TXN_AMOUNT: "1",
      WEBSITE: "APPSTAGING",
      CALLBACK_URL: "https://securegw-stage.paytm.in/theia/paytmCallback?ORDER_ID=ORDER0000000005",
      EMAIL: "saajan@playone.in",
      MOBILE_NO: "9810002539",
      ENVIRONMENT: "staging",
    }
after that sending request to paytm server with checksum hash
	var options = {
      REQUEST_TYPE: "DEFAULT",
      MID: "Playon05025317561797",
      ORDER_ID: "ORDER0000000004",
      CUST_ID: "CUSTID_0000000004",
      INDUSTRY_TYPE_ID: "Retail",
      CHANNEL_ID: "WAP",
      TXN_AMOUNT: "1",
      WEBSITE: "APPSTAGING",
      CALLBACK_URL: "https://securegw-stage.paytm.in/theia/paytmCallback?ORDER_ID=ORDER0000000004",
      EMAIL: "saajan@playone.in",
      MOBILE_NO: "9810002539",
      ENVIRONMENT: "staging",
      CHECKSUMHASH: "xxx"
    }

**Comment by ArunYogi** [comment]
@luckyplayone , I dont see "CHECKSUM" as part of the request, that field is mandatory. Please gothrough the readme file once and paytm developer documentation to validate the info you are sending to paytm.

**Comment by luckyplayone** [comment]
@ArunYogi checksum hash is also sending
