### ISSUE TITLE
where can we find declaration.d.ts ?

### ISSUE THREAD

**Issue by Srijita173** [ArunYogi/paytm-cordova-plugin#21]
Installed the plugin in phonegap CLI . The plugin gets added and necessary changes reflect in config.xml . Please help me in knowing where and how can I find the declaration.d.ts file .

**Comment by ArunYogi** [comment]
@Srijita173 , declaration.d.ts will be present in ionicv2 based projects. In ionicv3 it was removed.
You could just mention below line in the .ts file where you are initiating the transaction.
`declare var paytm: any;`
