### ISSUE TITLE
Paytm Link Wallet

### ISSUE THREAD

**Issue by luckyplayone** [ArunYogi/paytm-cordova-plugin#22]
Hi @ArunYogi. I Hope you are doing. 

could you please help me to link paytm wallet in my ionic application ? 
Looking forward to hear from you

**Comment by ArunYogi** [comment]
@luckyplayone , go through the [readme](https://github.com/ArunYogi/paytm-cordova-plugin/blob/master/README-IONIC.md) to know how you can integrate paytm gateway with ionic application. Paytm gateway has link to  paytm wallet as well, so paytm wallet login will be shown while u start a transaction with paytm gateway.
if I misunderstood your question, please brief me.

**Comment by luckyplayone** [comment]
@ArunYogi as per the document I have integrated the paytm in my application and it's working perfectly but how do I link paytm in my application so that i can show the balance of the paytm wallet in my application and  every time user comes to payment page the balance will appear.

**Comment by ArunYogi** [comment]
@luckyplayone , this is Paytm related question and not related to this plugin. Paytm team is correct entity to ask this question. Go through this [Auto Debit](https://developer.paytm.com/docs/v1/auto-debit-payment) link once, which talks about auto-debit function, as part of the function, you could link customer's Paytm wallet balance.
Ref: 
[Sent OTP API](https://developer.paytm.com/docs/send-otp-api/) 
[Validate OTP API](https://developer.paytm.com/docs/validate-otp-api/)
[Check Balance API](https://developer.paytm.com/docs/check-balance-api/)
Note: Further Certificate based service is not done in this app, yet.
