### ISSUE TITLE
Transaction abandoned from CCAvenue

### ISSUE THREAD

**Issue by jitdhar** [ArunYogi/paytm-cordova-plugin#23]
Every time i procced to do payment the error coming up is 402:Transaction abandoned from CCAvenue
Please help ASAP

**Comment by vivekgotraj** [comment]
> Every time i procced to do payment the error coming up is 402:Transaction abandoned from CCAvenue
> Please help ASAP

hi @jitdhar, have you solve this issue

**Comment by ArunYogi** [comment]
@jitdhar , this seems to be paytm related to issue and not this plugin related. Pelase contact Paytm team with complete request body for better resolution with them.

**Comment by Giddu** [comment]
Hi @jitdhar , I solved this issue by using 'WEBSTAGING' instead of 'APPSTAGING'. Hope it helps you.

**Comment by ArunYogi** [comment]
@jitdhar , is issue got resolved ? giving the options send to the plugin helps to identify the issue..
