### ISSUE TITLE
'LOST IN SPACE' page 

### ISSUE THREAD

**Issue by ghost** [ArunYogi/paytm-cordova-plugin#25]
i am trying to add paytm payment gateway to a cordova app.
The checksum is being generated but i am getting transfered to Lost in Space page says 'session expired'

let txnRequest = {
        "MID": "AIoJSB06647351746673", // PayTM Credentials
        "ORDER_ID": "ORDER0000000411", // Should be unique for every order.
        "CUST_ID": "CUSTOMER0001",
        "INDUSTRY_TYPE_ID": "Retail", // PayTM Credentials
        "CHANNEL_ID": "WAP", // PayTM Credentials
        "TXN_AMOUNT": "1", // Transaction Amount should be a String
        "WEBSITE": "APPSTAGING" // PayTM Credentials
      }
      const successCallback = (response) => {
        console.log('success', response)
      }
      const failureCallback = (error) => {
        console.log('Failure', error)
      }
      txnRequest.CALLBACK_URL = "https://securegw-stage.paytm.in/theia/paytmCallback?ORDER_ID=" + txnRequest.ORDER_ID
      paytm_checksum.genchecksum(txnRequest, '******', function (err, checksum) {
        txnRequest["CHECKSUMHASH"] = checksum
        txnRequest["ENVIRONMENT"] = "staging"
        console.log(txnRequest) 
//OUTPUT OF txnRequest
// CALLBACK_URL: "https://securegw-stage.paytm.in/theia/paytmCallback?ORDER_ID=ORDER0000000411"
        // CHANNEL_ID: "WAP"
        // CHECKSUMHASH: "4LMMteW4mUioTKMySoUSZNcIboLN/t6XRex1DPxScZ+M0vOJEMt6nzKgl6TMK8qYSSxUaTD/tRtfvLRnVpAjou7j42wOD8G5lPzXlAMQOBA="
        // CUST_ID: "CUSTOMER0001"
        // ENVIRONMENT: "staging"
        // INDUSTRY_TYPE_ID: "Retail"
        // MID: "AIoJSB06647351746673"
        // ORDER_ID: "ORDER0000000411"
        // TXN_AMOUNT: "1"
        // WEBSITE: "APPSTAGING"
        window.paytm.startPayment(
          txnRequest,
          successCallback,
          failureCallback
        );
      });

**Comment by ArunYogi** [comment]
@eggandmoney,
Does paytm error page shows any other information apart from "Lost in space", because sometime, if param is wrong paytm shown the incorrect information in the same page. If that's the not case, please get `adb log` along with params and post to paytm for resolution.
