### ISSUE TITLE
Live Transaction 

### ISSUE THREAD

**Issue by luckyplayone** [ArunYogi/paytm-cordova-plugin#27]
Hi @ArunYogi, 

I can't able to do the live transaction with this plugin everytime it returns invalid checksum. 

please help me. here's the params,

{"REQUEST_TYPE": "DEFAULT", "MID":"XXX",
"ORDER_ID":"ORDERID_80","CUST_ID":"CUSTID_80","INDUSTRY_TYPE_ID":"Retail","CHANNEL_ID":"WAP","TXN_AMOUNT":"1","WEBSITE":"DEFAULT","CALLBACK_URL":"https://securegw.paytm.in/theia/paytmCallback?ORDER_ID=ORDERID_80","EMAIL":"saajan@playone.in","MOBILE_NO":"9810002539"}

**Comment by ArunYogi** [comment]
@luckyplayone , 
Invalid checksum is a message from Paytm, this means the checksum send to Paytm site is not a valid one. Further I dont see a checksum in the param you have posted here. Please read the "Readme" file completely.

**Comment by luckyplayone** [comment]
Here's the final params for production

CALLBACK_URL: "https://securegw.paytm.in/theia/paytmCallback?ORDER_ID=ORDERID_6"
CHANNEL_ID: "WAP"
CHECKSUMHASH: "1AYspr6I+tZ3VJg8890gggms2vxFMtPioUaQSUrvfrY7eFM9J6x1LEQYlPaG4nbZUqweUBTnRX5I85vurkjazwYgLBplrr+/tSJXt7OFmzI="
CUST_ID: "CUSTID_6"
EMAIL: "saajan@playone.in"
ENVIRONMENT: "production"
INDUSTRY_TYPE_ID: "Retail"
MID: "xxx"
MOBILE_NO: "9810002539"
ORDER_ID: "ORDERID_6"
TXN_AMOUNT: "1"
WEBSITE: "DEFAULT"

**Comment by luckyplayone** [comment]
I am confused in REQUEST_TYPE: "DEFAULT", what should i passed in this ?

**Comment by ArunYogi** [comment]
@luckyplayone , That info was requested by Paytm previously, now they are not asking for it. so you dont have to send that details ot paytm plugin or checksum creation.

**Comment by luckyplayone** [comment]
@ArunYogi What should i do ? as per your documentation, I am doing the same thing as you said. the only thing i am not passing this parameter because they don't provide me. 
REQUEST_TYPE: "DEFAULT"

**Comment by ArunYogi** [comment]
@luckyplayone , send it or dont send it. it wont make a difference, because currently in my app,, I am sending this field and its working (both in test and production)

**Comment by luckyplayone** [comment]
@ArunYogi Okay !!

**Comment by luckyplayone** [comment]
@ArunYogi what value are you passing in WEBSITE for staging?

**Comment by ArunYogi** [comment]
@luckyplayone , WEBSTAGING. for WEB channel, you should not use this plugin.

**Comment by luckyplayone** [comment]
@luckyplayone which plugin then i used?

**Comment by ArunYogi** [comment]
@luckyplayone , please go through the web site integration document in paytm for the same.. you have to post param to paytm site and should ask paytm to redirect to your server/web app after processing payment.

**Comment by ArunYogi** [comment]
As your channel is WEB, this form is not for that channel. Closing this issue

**Comment by luckyplayone** [comment]
@ArunYogi I am using this plugin in my ionic application. i am facing some problem that's why i am here. please help me.

**Comment by ArunYogi** [comment]
> Here's the final params for production
> 
> CALLBACK_URL: "https://securegw.paytm.in/theia/paytmCallback?ORDER_ID=ORDERID_6"
> CHANNEL_ID: "WAP"
> CHECKSUMHASH: "1AYspr6I+tZ3VJg8890gggms2vxFMtPioUaQSUrvfrY7eFM9J6x1LEQYlPaG4nbZUqweUBTnRX5I85vurkjazwYgLBplrr+/tSJXt7OFmzI="
> CUST_ID: "CUSTID_6"
> EMAIL: "[saajan@playone.in](mailto:saajan@playone.in)"
> ENVIRONMENT: "production"
> INDUSTRY_TYPE_ID: "Retail"
> MID: "xxx"
> MOBILE_NO: "9810002539"
> ORDER_ID: "ORDERID_6"
> TXN_AMOUNT: "1"
> WEBSITE: "DEFAULT"

in this check the website detail. Paytm would give u MID,INDUSTRY_TYPE_ID,WEBSITE and MERCHANT_KEY separately for development and production. Here I can see that you are mixing production and development credentials (sending development credentials to production environment).

**Comment by luckyplayone** [comment]
@luckyplayone Thanks !!
