### ISSUE TITLE
Got error Redirecting back to app Message 

### ISSUE THREAD

**Issue by siva563** [ArunYogi/paytm-cordova-plugin#28]
Hello Everyone, 

I am trying integrate Paytm Payment gateway to my App for both (iOS and Android).

**`I am using : Ionic 4 and back-end is : Java`**

I am able generate Checksum value using below Request Object 

```
var requestObject = {
            "merchantId": "merchent_ID",
            "paymentOrderId": "RDER0000000014",
            "merchantKey": "merchent_key",
            "channelId": "WAP",
            "donorId": "10000981",
            "mobileNo": "mobileNumber",
            "email": "abc@gmail.com",
            "transactionAmount": "100.00",
            "website": "APPSTAGING",
            "industryTypeId": "Retail",
            "callbackUrl": "https://securegw.paytm.in/theia/paytmCallback?paymentOrderId=ORDER0000000014"
        };   
```

Once I got checksum value I am trying using below code hit Paytm Server :

```
 options = {
            "ENVIRONMENT": "staging",
            "REQUEST_TYPE": "DEFAULT",
            "MID": "MID",
            "ORDER_ID": "ORDER0000000014",
            "CUST_ID": "10000981",
            "INDUSTRY_TYPE_ID": "Retail",
            "CHANNEL_ID": "WAP",
            "TXN_AMOUNT": "100.00",
            "WEBSITE": "APPSTAGING",
            "CALLBACK_URL": "https://securegw.paytm.in/theia/paytmCallback?ORDER_ID=ORDER0000000014",
            "EMAIL": "abc@gmail.com",
            "MOBILE_NO": "mobileNumber",
            "CHECKSUMHASH": checkSum
        };
```

paytm.startPayment(options, this.suc, this.suc);

But I am getting message in screen :  `Redirecting back to app` . it is not redirecting at all. 

could you please someone help me out, solve this issue.  @ArunYogi your help is required, could you please help me.

Thanks in advance !!!

**Comment by ArunYogi** [comment]
@siva563 , is Paytm taking to card/bank info collection screen or it takes directly to "Redirecting back to app" screen? . Further getting stuck with "Redirecting back to app" issue should have been resolved with new paytm library 1.3.3. Get android logs for the same and see whether paytm throws any information related to this.. Paytm is the one who has to answer about this issue.

**Comment by ArunYogi** [comment]
@siva563 , issue got resolved ? i see you are sending staging credentials to production url..

**Comment by manojbharti** [comment]
@ArunYogi I am getting the same issue plz help asap.

**Comment by pratikbh** [comment]
@ArunYogi I am getting this issue when there is failure from bank end (When I select Failure after entering card details). For successful payment , `successCallback` is called and it works fine. I tried using the `master` branch for this plugin, still there is same issue. Android logs don't show anything relevant. 

<img width="366" alt="Screenshot 2019-12-22 at 3 29 31 PM" src="https://user-images.githubusercontent.com/10649742/71320333-e3637e00-24cf-11ea-8d6b-ca60f95735c7.png">

Request

```
{
  "MID":"merchantId",
  "ORDER_ID":"30",
  "CUST_ID":"10",
  "INDUSTRY_TYPE_ID":"Retail",
  "CHANNEL_ID":"WAP",
  "TXN_AMOUNT":"5",
  "MOBILE_NO":"5522233445",
  "EMAIL":"iii@fff.com",
  "WEBSITE":"WEBSTAGING",
  "CALLBACK_URL":"https://securegw-stage.paytm.in/theia/paytmCallback?ORDER_ID=30",
  "ENVIRONMENT":"staging",
  "CHECKSUMHASH":"checkSum"
}
```

**Comment by ArunYogi** [comment]
@pratikbh , Please create a new issue, rather than commenting in closed issue. This will go unnoticed. 
Further this is a Paytm Library issue and not this plugin issue. As per Paytm's solution on this topic is to upgrade the library version to 1.3.3, which is what this plugin uses. If we are still facing the issue, we can do an upgrade of paytm plugin. If we still faces the issue, Need to reach Paytm for the solution.

**Comment by rahulseth625** [comment]
If anybody solved this problem . Kindly please reply how to get over this.
