### ISSUE TITLE
@ArunYogi Sir I have almost done but one minor issue has been left that is checksum is invalid please resolve this issue.

### ISSUE THREAD

**Issue by manmohanagarwal4** [ArunYogi/paytm-cordova-plugin#29]
options: any = {
    ENVIRONMENT: "staging", // environment details. staging for test environment & production for live environment
    REQUEST_TYPE: "DEFAULT", // You would get this details from paytm after opening an account with them
    MID: "YxXRuE02376623161940", // You would get this details from paytm after opening an account with them
    ORDER_ID: environment.orderId, // Unique ID for each transaction. This info is for you to track the transaction details
    CUST_ID: environment.custId, // Unique ID for your customer
    INDUSTRY_TYPE_ID: "Retail", // You would get this details from paytm after opening an account with them
    CHANNEL_ID: "WAP", // You would get this details from paytm after opening an account with them
    TXN_AMOUNT: "1", // Transaction amount that has to be collected
    WEBSITE: "APPSTAGING", // You would get this details from paytm after opening an account with them
    CALLBACK_URL: "https://securegw-stage.paytm.in/theia/paytmCallback?ORDER_ID=" + environment.orderId,
    EMAIL: "abc@gmail.com", // Email of customer
    MOBILE_NO: "9999999999", // Mobile no of customer
    PAYTM_MERCHANT_KEY: "vq&kDxXstaeidGJr"
  }; 
I am sending these upper information to server to generating the checksum and after that in front end with checksum starting payment then in success callback the error is checksum is invalid.

**Comment by manudev91** [comment]
I am facing the same issue :(

**Comment by pratikchourdia** [comment]
Well even tried for more than 2 hours but  Having same issue.. Please help

**Comment by manudev91** [comment]
Mine is resolved :)

I have followed the given steps and now it's working fine

**Comment by manudev91** [comment]
let options = {
			MID: "******", 
			ORDER_ID: orderid,
			CUST_ID: "CUST001", 
			INDUSTRY_TYPE_ID: "Retail", 
			CHANNEL_ID: "WAP", 
                        TXN_AMOUNT: "1", 
			WEBSITE: "WEBSTAGING",
                        CALLBACK_URL: "https://securegw-stage.paytm.in/theia/paytmCallback?ORDER_ID=" + orderid,
			ENVIRONMENT: "staging"
		};

I am using this information for generating the checksum.

**Comment by pratikchourdia** [comment]
Yeah, Even Mine too.. I was having issue with REQUEST_TYPE as it was passing on View but was forgetting it on my checksum generator..
Thanks :)

**Comment by softwebtech** [comment]
Hi, guys
I am facing same problem as `Invalid checksum` till 2 days..
I followed all step suggest here but till no result.. please, help me..

**Comment by softwebtech** [comment]
Hey, I also solved the checksum issue.. using
`Note: Checksum has to be created without "ENVIRONMENT" field. This field is for internal use only.`
