### ISSUE TITLE
libPaymentsSDK.a(Reachability.o)...Undefined symbols for architecture x86_64

### ISSUE THREAD

**Issue by kbmanikanta** [ArunYogi/paytm-cordova-plugin#3]
Undefined symbols for architecture x86_64:
  "_SCError", referenced from:
      -[Paytm_Reachability startNotifier] in libPaymentsSDK.a(Reachability.o)
  "_SCNetworkReachabilityGetFlags", referenced from:
      -[Paytm_Reachability isReachable] in libPaymentsSDK.a(Reachability.o)
      -[Paytm_Reachability isReachableViaWWAN] in libPaymentsSDK.a(Reachability.o)
      -[Paytm_Reachability isReachableViaWiFi] in libPaymentsSDK.a(Reachability.o)
      -[Paytm_Reachability connectionRequired] in libPaymentsSDK.a(Reachability.o)
      -[Paytm_Reachability isConnectionOnDemand] in libPaymentsSDK.a(Reachability.o)
      -[Paytm_Reachability isInterventionRequired] in libPaymentsSDK.a(Reachability.o)
      -[Paytm_Reachability reachabilityFlags] in libPaymentsSDK.a(Reachability.o)
      ...
  "_SCErrorString", referenced from:
      -[Paytm_Reachability startNotifier] in libPaymentsSDK.a(Reachability.o)
  "_SCNetworkReachabilitySetDispatchQueue", referenced from:
      -[Paytm_Reachability startNotifier] in libPaymentsSDK.a(Reachability.o)
      -[Paytm_Reachability stopNotifier] in libPaymentsSDK.a(Reachability.o)
  "_SCNetworkReachabilitySetCallback", referenced from:
      -[Paytm_Reachability startNotifier] in libPaymentsSDK.a(Reachability.o)
      -[Paytm_Reachability stopNotifier] in libPaymentsSDK.a(Reachability.o)
  "_SCNetworkReachabilityCreateWithAddress", referenced from:
      +[Paytm_Reachability reachabilityWithAddress:] in libPaymentsSDK.a(Reachability.o)
  "_SCNetworkReachabilityCreateWithName", referenced from:
      +[Paytm_Reachability reachabilityWithHostname:] in libPaymentsSDK.a(Reachability.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

** BUILD FAILED **

The following build commands failed:
	Ld build/emulator/RevalShop.app/RevalShop normal x86_64
(1 failure)

**Comment by kbmanikanta** [comment]
can you help me to fix this issue?

**Comment by kbmanikanta** [comment]
I have installed this plugin on ios platform and build..

**Comment by ArunYogi** [comment]
This issue should have been solved with latest XCode and ios-deploy. what version your are using ?
