### ISSUE TITLE
Request for help for generating checksum

### ISSUE THREAD

**Issue by dexterprabhakar** [ArunYogi/paytm-cordova-plugin#31]
Hi @YaMo97 @ArunYogi , We are trying to use this plugin for integration of paytm  in our cordova application.
We are stuck at checksum point and has no idea how it will be generated within mobile application.

Would be really helpful if anyone can guide us for the same. 

Regards
Prabhakar

**Comment by ArunYogi** [comment]
Checksum has to be constructed at backend. Paytm provides checksum creation and validation utilities based on the platform , you have build your backend system.
check the list here https://github.com/Paytm-Payments?utf8=%E2%9C%93&q=checksum&type=&language=

**Comment by dexterprabhakar** [comment]
Hi Arun,
Thanks for quick reply. We also thought so just needed affirmation.
A small query, we do not understand where we have to do :
Declare car paytm: any;
As per docs it needs to be done in .ts file. There is no such declaration file in our cordova project. 
Would appreciate your guidance .
RegardsGet Outlook for Android

**Comment by dexterprabhakar** [comment]
Hi @ArunYogi @YaMo97 any idea how to do this ?

Add below line to declaration.d.ts file

declare var paytm : any;

*we dont have any declaration.d.ts file

**Comment by ArunYogi** [comment]
> Hi @ArunYogi @YaMo97 any idea how to do this ?
> 
> Add below line to declaration.d.ts file
> 
> declare var paytm : any;
> 
> *we dont have any declaration.d.ts file

Please refer this link https://github.com/ArunYogi/paytm-cordova-plugin/blob/master/README-IONIC.md

**Comment by dexterprabhakar** [comment]
thanks @ArunYogi  but we are not in ionic. We are using cordova.

**Comment by ArunYogi** [comment]
> thanks @ArunYogi but we are not in ionic. We are using cordova.

that's fine, the core concept is, you have to declare a global variable named "Paytm" at the start of the file (where you are accessing the payment details) and start calling method mentioned in read me file.

**Comment by dexterprabhakar** [comment]
Hi @ArunYogi @YaMo97 finally we have been able to access the paytm plugin. We are also able to start the transcation. The startPayment function starts the flow, opens the paytm payment page for a fraction of second and then sends the callback in success. In success we gets transcation failure because of invalid checksum.

Point to be highlighted here is the same web and backend code is working fine from website. we are able to make successful transcations from there but not from the plugin. 

Your help will be really appriciated.

**Comment by dexterprabhakar** [comment]
Hi @ArunYogi we have sorted the issue with keys. the paytm plugin is working ok on android environment. 
Now we have issue with ios environment where its giving us missing key error with response code -1. we are sending txn amount as string only. any ideas what could be wrong ???

**Comment by ArunYogi** [comment]
@dexterprabhakar , please post the request u are sending to the plugin and simulator logs... With these information, I can assist you.

**Comment by dexterprabhakar** [comment]
![Screenshot 2019-09-17 at 5 43 37 PM](https://user-images.githubusercontent.com/42892365/65040816-e56aed80-d972-11e9-8a72-4a183f36c281.png)
The first options are from my backend server.
The second options are what i  am sending to paytm plugin.
last line is what am getting in failure callback

**Comment by dexterprabhakar** [comment]
@ArunYogi these are logs from xCode. something weird. as per these logs payTM plugin not found.
![Screenshot 2019-09-17 at 5 56 58 PM](https://user-images.githubusercontent.com/42892365/65041613-cbcaa580-d974-11e9-8276-2751db9d8dc8.png)

**Comment by ArunYogi** [comment]
@dexterprabhakar , 
"CDVPlugin class PayTMCordova (pluginName:PaytM)  does not exists" -> The plugin is not installed in iOS platform properly. Please remove and add the plugin.

Further I hope you are trying this in sandbox environment and not production. 
 * The  "Retail" in INDUSTRY_TYPE_ID fields, says that u r trying for sandbox environment. But "ENVIRONMENT" field holds "production" value. This mismatch should be resolved with proper value based on the environment you are trying.
* CUST_ID field holds only String value, you are sending a number formatted data. Please change it.
* You don't have to specify callback url, this plugin will take care of it.
* Please check the value for WEBSITE as well.

**Comment by dexterprabhakar** [comment]
@ArunYogi thanks for the input.

1. The plugin in earlier screenshot was not installed properly. PFA updated screenshot.
2. This is production environment and same values are being sent from android. (Industry type, cust id and environment)
3. Callback url is not used anywhere its website code fallback
![Screenshot 2019-09-17 at 6 08 03 PM](https://user-images.githubusercontent.com/42892365/65042464-827b5580-d976-11e9-9e72-3198e739a51b.png)

**Comment by dexterprabhakar** [comment]
@ArunYogi looks like it was customer id issue only. we changed it to string and its working now.
Thanks for your support. 

cheers
