### ISSUE TITLE
ERROR ReferenceError: paytm is not defined

### ISSUE THREAD

**Issue by clickervinod** [ArunYogi/paytm-cordova-plugin#32]
hi,

I have followed your steps but I am getting this error on browser test

`Tab1Page.html:21 ERROR ReferenceError: paytm is not defined`

I have declared it in ts file 

Please help

**Comment by ArunYogi** [comment]
This plugin doesnt support browser. It can be tested in simulator or real device

**Comment by ArunYogi** [comment]
Closing this issue, as there is no reply
