### ISSUE TITLE
how to integrate 'paytm-cordova-plugin' plugin into a phonegap app

### ISSUE THREAD

**Issue by ssanjoris** [ArunYogi/paytm-cordova-plugin#33]
Hi,

Can you please provide the steps to integrate this in to phonegap app?

Thanks & Regards,
Saji

**Comment by ArunYogi** [comment]
Please read the readme https://github.com/ArunYogi/paytm-cordova-plugin/blob/master/Readme.md file once. The instructions are for integration with phonegap/cordova based application
