### ISSUE TITLE
Paytm integration in ionic-4

### ISSUE THREAD

**Issue by manojbharti** [ArunYogi/paytm-cordova-plugin#37]
@ArunYogi, Please guide me to use this plugin with ionic version 4.

**Comment by ArunYokesh1** [comment]
whats the issue u r facing with steps from Readme file.

**Comment by manojbharti** [comment]
@ArunYokesh1 I don't have declaration.d.ts file in my app so I am not able to understand where and which file i need to use in place of declaration.d.ts. Please guide me I am using ionic's version 4.12

**Comment by ArunYokesh1** [comment]
@manojbharti ,
checkout ionic specific documentation
https://github.com/ArunYogi/paytm-cordova-plugin/blob/master/README-IONIC.md

**Comment by manojbharti** [comment]
@ArunYokesh1  I follow the steps from the link you provide but not worked. Can you please make a file of working paytm transaction it would be a great help for me.

**Comment by manojbharti** [comment]
@ArunYogi you added label "Help Wanted" but you didn't help. I am struglling with this plugin since a very long time also followed your README instruction but it didn't work for me.   Can you please provide working code.

**Comment by ArunYogi** [comment]
@manojbharti , This is actually "Help wanted" case, I have given my help based on the input you have given to me. I have created a new ionic 4 app and injected this plugin. It worked without any extra modification. Just by saying "it didnt work" , doesn't give much insight into whats going wrong. you have to explain more on whats going wrong.

**Comment by manojbharti** [comment]
@ArunYogi  please provide me that app which you just created with this plugin, It will be great help.

**Comment by manojbharti** [comment]
@ArunYogi I followed the steps from the Readme file which you provide above, but i am not able to understand step 7.
Where to call plugin please help

**Comment by Dipak26** [comment]
I called this plugin in ionic 5 and get paytm web UI my only concern is how I call the my angular api from there successcallback and error callback function. Because I am not able to get my component reference inside their callback in angular 10.
