### ISSUE TITLE
Reference Error: can't find variable: paytm

### ISSUE THREAD

**Issue by msuhaibk** [ArunYogi/paytm-cordova-plugin#8]
I am using **ionic 3.9.2**  and trying to integrate **paytm payment gateway** in my ionic app.
There are no plugins available with proper integration guidelines and it seems like the **road less travelled**.

I followed your guidelines and have basic understanding of plugins.
  
but it showed error **"paytm is undefined"**. After little research i wrapped my **startPayment** function in platform.ready then it showed **"Error: Uncaught (in promise): ReferenceError: paytm is not defined"**  

Thanks in Advance.

**Comment by ArunYogi** [comment]
Paytm plugin is available as global variable. Add below lines as part of import in the <page>.ts where you are triggering paytm.startPayment(...)

`declare var paytm: any;`

In application using ionic version <3, you can mention the same line in declaration.ts, then you can refer "paytm" anywhere in the application.

**Comment by YaMo97** [comment]
For Ionic,  try using this: - 

`(<any>window).paytm.startPayment(options, successCallback, failureCallback);`

**Comment by ArunYogi** [comment]
@YaMo97 , there are two application currently in production using this plugin which are running without any issues..
Try removing the platform and add it again. Sometime the plugin is not installed properly might be causing this issue

**Comment by ArunYogi** [comment]
Closing this question issue, as @YaMo97 , has posted successful Paytm PG launch in [this issue](https://github.com/ArunYogi/paytm-cordova-plugin/issues/9#issuecomment-418403662)

**Comment by gsabishek** [comment]
still i am lagging on this issue...help me to sort out this issue..
"paytm is not defined"
